[project]
name = "stepper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.11.0.86",
    "pillow>=11.1.0",
    "pypylon>=4.1.0",
    "pyserial>=3.5",
    "toml>=0.10.2",
    "ultralytics>=8.3.218",
]
